version: 2

# Specify os and python version
build:
  os: "ubuntu-24.04"
  tools:
    python: "3.13"
  jobs:
    create_environment:
      - asdf plugin add uv
      - asdf install uv latest
      - asdf global uv latest
      - UV_PROJECT_ENVIRONMENT=$READTHEDOCS_VIRTUALENV_PATH uv sync --all-extras --group docs
    install:
      - "true"

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/src/conf.py

# Optionally build your docs in additional formats such as PDF and ePub
formats: all
